In [1]:
import torch

In [35]:
a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([3.], requires_grad=True)
a, b
x = a * b
y = x * 2
params = [a,b,x,y]
for p in params: p.retain_grad()
y.backward()
[p.grad for p in params]

[tensor([6.]), tensor([4.]), tensor([2.]), tensor([1.])]

In [111]:
t = torch.arange(1, 13, dtype=torch.float).view((3,4))
t.sum(1, keepdim=True), t[0]

(tensor([[10.],
         [26.],
         [42.]]),
 tensor([1., 2., 3., 4.]))

In [129]:
a = torch.arange(1, 13, dtype=torch.float).view((3,4))#.view((1,12))#.view((3,4))
a.requires_grad=True
b = torch.arange(1, 4, dtype=torch.float).view((3,1))
b.requires_grad=True
c = a.sum(1, keepdim=True)
d = (a * c).sum()
# cc = c**(0.5)
# d = a * cc
# e = d.sum()
params = [a,c,d]
for p in params:
    print(p)
    p.retain_grad()
params[-1].backward()
[p.grad for p in params]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], requires_grad=True)
tensor([[10.],
        [26.],
        [42.]], grad_fn=<SumBackward1>)
tensor(2540., grad_fn=<SumBackward0>)


[tensor([[20., 20., 20., 20.],
         [52., 52., 52., 52.],
         [84., 84., 84., 84.]]),
 tensor([[10.],
         [26.],
         [42.]]),
 tensor(1.)]

In [136]:
(c + a.sum(1, keepdim=True).repeat(1,a.shape[1]))

tensor([[20., 20., 20., 20.],
        [52., 52., 52., 52.],
        [84., 84., 84., 84.]], grad_fn=<AddBackward0>)